# Generated by Django 5.2 on 2025-04-23 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('option_a_text', models.CharField(blank=True, max_length=255, null=True)),
                ('option_b_text', models.CharField(blank=True, max_length=255, null=True)),
                ('is_ending', models.BooleanField(default=False)),
                ('option_a_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_option_a', to='stories.storynode')),
                ('option_b_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_option_b', to='stories.storynode')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='stories.story')),
            ],
        ),
    ]
