# Generated by Django 5.2 on 2025-05-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_storynode'),
    ]

    operations = [
        migrations.AddField(
            model_name='storynode',
            name='is_start',
            field=models.BooleanField(default=False),
        ),
    ]
